"""Veri kaynağı yönetimi domain bileşenleri."""

from veri_kalitesi.data_sources.connectors import CSVConnector, ConnectorRegistry
from veri_kalitesi.data_sources.models import (
    ConnectionTestResult,
    DataSource,
    DataSourceStatus,
    DataField,
    DataProfile,
    Dataset,
    DatasetType,
    ErrorClass,
    MetadataChange,
    MetadataChangeType,
    MetadataDatasetCandidate,
    MetadataDiscoveryOptions,
    MetadataDiscoveryResult,
    MetadataFieldCandidate,
    ProfileComputationResult,
    ProfileMethod,
    ProfileOptions,
    ProfileStatus,
    SourceType,
)
from veri_kalitesi.data_sources.postgresql import (
    AuthenticationConnectionError,
    DNSConnectionError,
    DriverConnectionError,
    NetworkConnectionError,
    PermissionConnectionError,
    PostgreSQLConnector,
    PostgreSQLProbeResult,
    TLSConnectionError,
    TimeoutConnectionError,
    is_read_only_sql,
)
from veri_kalitesi.data_sources.repository import SQLiteDataSourceRepository
from veri_kalitesi.data_sources.secrets import EmptySecretResolver, InMemorySecretResolver
from veri_kalitesi.data_sources.service import DataSourceService
from veri_kalitesi.data_protection import (
    ClassificationCode,
    DataProcessingInventory,
    InventoryCoverageReport,
    InventoryCoverageStatus,
    InventoryCoverageTechnicalError,
)

__all__ = [
    "AuthenticationConnectionError",
    "CSVConnector",
    "ClassificationCode",
    "ConnectionTestResult",
    "ConnectorRegistry",
    "DNSConnectionError",
    "DataSource",
    "DataSourceService",
    "DataSourceStatus",
    "DataField",
    "DataProfile",
    "DataProcessingInventory",
    "InventoryCoverageReport",
    "InventoryCoverageStatus",
    "InventoryCoverageTechnicalError",
    "Dataset",
    "DatasetType",
    "DriverConnectionError",
    "EmptySecretResolver",
    "ErrorClass",
    "InMemorySecretResolver",
    "MetadataChange",
    "MetadataChangeType",
    "MetadataDatasetCandidate",
    "MetadataDiscoveryOptions",
    "MetadataDiscoveryResult",
    "MetadataFieldCandidate",
    "NetworkConnectionError",
    "PermissionConnectionError",
    "ProfileComputationResult",
    "ProfileMethod",
    "ProfileOptions",
    "ProfileStatus",
    "PostgreSQLConnector",
    "PostgreSQLProbeResult",
    "SQLiteDataSourceRepository",
    "SourceType",
    "TLSConnectionError",
    "TimeoutConnectionError",
    "is_read_only_sql",
]
